### ISSUE TITLE
Use SHA1 instead of MD5

### ISSUE THREAD

**Issue by justquick** [ericflo/django-newcache#1]
The md5 algorithm is very vulnerable to collisions and should not be used for generating hash keys from large amounts of input data especially if that data contains whitespace which your README says this module should be able to handle. Is there any particular reason why md5 was chosen over sha1? md5 hashes are 8 characters shorter than sha1s' which is my guess why it was chosen, but its not worth the risk of using it which could result in cache collisions and very bad results on your site. For more info on the crypto side of things checkout this article on the vulnerability of MD5: http://www.kb.cert.org/vuls/id/836068

I have been working on a patch to this which uses sha1 (from django.utils.hashcompat) to hash the keys instead of md5. My fork is available at http://github.com/justquick/django-newcache

**Comment by justquick** [comment]
fixed in v0.2.2

**Comment by ericflo** [comment]
Thanks for the patch!
