### ISSUE TITLE
Compatibility with johnny-cache

### ISSUE THREAD

**Issue by gtaylor** [ericflo/django-newcache#5]
I wasn't sure of the best way to go about this, so figured I'd post here for consideration. We use johnny-cache for one of our projects, and were excited about django-newcache, until we saw that it doesn't work out-of-the-box as intended with johnny-cache.

http://packages.python.org/johnny-cache/backends.html

As best as I could find, a timeout of 0 for django-newcache was just 0 seconds. I realize I can sub-class their backend subclasses, but figured I'd mention this here, as the popularity of johnny-cache is rising. Perhaps this is behavior that would be desirable for django-newcache?

Just thought I'd bring it up for the sake of providing food for thought.

**Comment by bkonkle** [comment]
Looking at the code, I believe the current version of newcache should be compatible with johnny-cache as-is.  Here is newcache's approach:

```
def _get_memcache_timeout(self, timeout):
    """
    Memcached deals with long (> 30 days) timeouts in a special
    way. Call this function to obtain a safe value for your timeout.
    """
    if timeout is None:
        timeout = self.default_timeout
    if timeout > 2592000: # 60*60*24*30, 30 days
        # See http://code.google.com/p/memcached/wiki/FAQ
        # "You can set expire times up to 30 days in the future. After that
        # memcached interprets it as a date, and will expire the item after
        # said date. This is a simple (but obscure) mechanic."
        #
        # This means that we have to switch to absolute timestamps.
        timeout += int(time.time())
    return timeout
```

Here is johnny-cache's approach:

```
    def _get_memcache_timeout(self, timeout=None):
        if timeout == 0: return 0
        return super(CacheClass, self)._get_memcache_timeout(timeout)
```

In both cases, if a timeout of 0 is used, then 0 is the return value of _get_memcache_timeout.

**Comment by gtaylor** [comment]
Thanks for looking at this, we'll give it a shot!
